services:
  vectordb:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=TRUE
      - PERSIST_DIRECTORY=/chroma/my_db
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    